// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTcx4_Qfw1fJQdedyBcfGcQrlVTFfOdVo',
    appId: '1:414799583916:web:d66e7ea53f2a5a429c1d09',
    messagingSenderId: '414799583916',
    projectId: 'schedule-d7c8d',
    authDomain: 'schedule-d7c8d.firebaseapp.com',
    storageBucket: 'schedule-d7c8d.appspot.com',
    measurementId: 'G-421KNMQX9D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBlslF3yrjGVSU5DLO93qbHCirR1BdtIE',
    appId: '1:414799583916:android:68f5ced6bc9c07299c1d09',
    messagingSenderId: '414799583916',
    projectId: 'schedule-d7c8d',
    storageBucket: 'schedule-d7c8d.appspot.com',
  );
}
